# Permalinks
permalink:        pretty

# Setup
title:            'cout << ym'
description:      "ufoym's blog"
url:              http://ufoymtest.github.io

author:
  name:           'Ming (ufoym)'
  url:            http://ufoym.com

paginate:         8

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/ufoym
